general:
  mode: train
  device: cuda
  seed: 42

logging:
  level: INFO
  format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
  colors: auto
  file: null
  capture_warnings: true
  events_to_log_in_debug: [0, 1000, 200000]
  train:
    output_dir: training_logs
    experiment_name: 1D_coupling_PN_256_correct_split


dataset:
  input_h5_path: data/Coupling_Inference_negW.h5
  max_events_per_parameter: 830000
  observables:
    - EVENT_PARTICLES: top1_pt
      transformation: LogScaler
    - EVENT_PARTICLES: top1_eta
      transformation: StandardScaler
    - EVENT_PARTICLES: top2_eta
      transformation: StandardScaler
    - EVENT_GLOBAL: mttbar
      transformation: StandardScaler
  parameters:
    - EVENT_GLOBAL: coupling
      transformation: MinMaxScaler
      values_for_training: [0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6]
      values_for_testing: [0.5, 1.1]
  weights:
    - EVENT_GLOBAL: lumiWeight
  train:
    num_workers: 10
    batch_size: 10240
  val:
    num_workers: 10
    batch_size: 10240


model:
  hidden_dim: 256
  dropout: 0.05

train:
  n_epochs: 150
  learning_rate: 0.0002
  weight_decay: 0.001
  lr_patience: 10
  lr_factor: 0.8
  signal_weight_sign: negative
  background_weight_sign: positive
  compile: false

predict:
  checkpoint_path: lightning_logs/version_0/checkpoints/
  output_file: results/predictions.csv

performance:
  checkpoint_path: training_logs/1D_coupling_PN_256_correct_split/version_0/checkpoints/
  output_dir: results/performance/1D_coupling_PN_256_correct_split/
  batch_size: 10240

inference:
  output_dir: results/inference/coupling_1p1_256_correct_split/
  model_pp_checkpoint: training_logs/1D_coupling_PP_256_correct_split/version_0/checkpoints/
  model_pn_checkpoint: training_logs/1D_coupling_PN_256_correct_split/version_0/checkpoints/
  observable: mttbar
  rosmm_sign: -1.0
  truth_parameter: 1.1
  theta_min: 0.1
  theta_max: 2.1
  n_points: 100
  n_pseudo_experiments: 10000
  pseudo_experiment_confidence: 0.95
  
input_plots:
  output_dir: results/input_plots/1D_coupling/
  n_bins: 100
  density: true
  signal_plus_background: true
  log_scale: true
  variables:
    - group: EVENT_PARTICLES
      name: top1_pt
      display_name: "Top1 $p_{T}$"
      x_min: 0
      x_max: 500
      x_label: "$p_{T}(t_1)$ [GeV]"
      y_label: "Density"
    - group: EVENT_PARTICLES
      name: top2_pt
      display_name: "Top2 $p_{T}$"
      x_min: 0
      x_max: 500
      x_label: "$p_{T}(t_2)$ [GeV]"
      y_label: "Density"
    - group: EVENT_PARTICLES
      name: top1_eta
      display_name: "Top1 $\\eta$"
      x_min: -5
      x_max: 5
      x_label: "$\\eta(t_1)$"
      y_label: "Density"
    - group: EVENT_PARTICLES
      name: top2_eta
      display_name: "Top2 $\\eta$"
      x_min: -5
      x_max: 5
      x_label: "$\\eta(t_2)$"
      y_label: "Density"
    - group: EVENT_GLOBAL
      name: mttbar
      display_name: "Invariant mass $t_1 t_2$ system"
      x_min: 500
      x_max: 1200
      x_label: "$m(t_1 ,t_2)$ [GeV]"
      y_label: "Density"
    - group: EVENT_GLOBAL
      name: coupling
      display_name: Coupling
      x_min: 0
      x_max: 2
      x_label: "$C_e$"
      y_label: "Density"
    - group: EVENT_GLOBAL
      name: lumiWeight
      display_name: "lumiWeight"
      x_min: -2
      x_max: 2
      use_weights: false