general:
  mode: train
  device: cuda
  seed: 42

logging:
  level: INFO
  format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
  colors: auto
  file: null
  capture_warnings: true
  train:
    output_dir: lightning_logs
    experiment_name: 2D_PP


dataset:
  input_h5_path: data/2D_Inference_negW.h5
  max_events_per_parameter: 700000
  observables:
    - EVENT_PARTICLES: top1_pt
      transformation: LogScaler
    - EVENT_PARTICLES: top2_pt
      transformation: LogScaler
    - EVENT_PARTICLES: top1_eta
      transformation: StandardScaler
    - EVENT_PARTICLES: top2_eta
      transformation: StandardScaler
    - EVENT_GLOBAL: mttbar
      transformation: StandardScaler
  parameters:
    - EVENT_GLOBAL: coupling
      transformation: MinMaxScaler
      values_for_training: [0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6]
      values_for_testing: [0.5, 1.1]
    - EVENT_GLOBAL: hmass
      transformation: MinMaxScaler
      values_for_training: [600.0, 700.0, 800.0, 900.0, 1000.0]
      values_for_testing: [650.0, 870.0]
  weights:
    - EVENT_GLOBAL: lumiWeight
  train:
    num_workers: 10
    batch_size: 10240
  val:
    num_workers: 10
    batch_size: 10240


model:
  hidden_dim: 64
  dropout: 0.05

train:
  n_epochs: 150
  learning_rate: 0.0002
  weight_decay: 0.001
  lr_patience: 10
  lr_factor: 0.8
  signal_weight_sign: positive
  background_weight_sign: positive
  compile: false

predict:
  checkpoint_path: lightning_logs/version_0/checkpoints/
  output_file: results/predictions.csv

performance:
  checkpoint_path: lightning_logs/2D_PP/version_0/checkpoints/
  output_dir: results/performance/2D_PP/
  batch_size: 10240

inference:
  output_dir: results/inference/coupling_1p1_hmass_870
  model_pp_checkpoint: lightning_logs/2D_PP/version_0/checkpoints/
  model_pn_checkpoint: lightning_logs/2D_PN/version_0/checkpoints/
  observable: mttbar
  rosmm_sign: 1.0
  truth_parameters:
    coupling: 1.1
    hmass: 870.0
  scan_parameters:
    - name: coupling
      min: 0.1
      max: 2.1
      n_points: 100
    - name: hmass
      min: 550.0
      max: 1150.0
      n_points: 100
